[project]
name = "celery-funboost-sample"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "celery>=5.5.3",
    "eventlet>=0.40.3",
    "gevent>=25.9.1",
    "redis>=6.4.0",
]
