version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.19.5
    container_name: elasticsearch
    privileged: true
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node # 单节点模式
      - xpack.security.enabled=false # 本地测试环境关闭默认安全认证
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
    networks:
      - local
    restart: unless-stopped

  kibana:
    image: kibana:8.19.5
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - local
    depends_on:
      - elasticsearch
    restart: unless-stopped

networks:
  local:
    driver: bridge